name: $(BuildDefinitionName)-$(SourceBranchName)-$(Date:yyyy.MM.dd)$(Rev:.rrr)
trigger:
  enabled: false
resources:
  pipelines:
  - pipeline: CI
    source: Common-WSODataStandard-TestBuild
    trigger:
      enabled: false
variables:
- name: PipelineResource
  value: CI
- name: BuildArtifact
  value: NugetPackages
stages:
- stage: MainStage
  pool:
    name: LocalS
  jobs:
  - job: MainJob
    steps:
    - task: 30f35852-3f7e-4c0c-9a88-e127b4f97211@1
      inputs:
        alias: $(PipelineResource)
        artifact: $(BuildArtifact)
        patterns: '**/*.nupkg'