trigger:
  branches:
    include:
    - master
pool:
  vmImage: ubuntu-latest
stages:
- stage: One
  jobs:
  - job: A
    steps:
    - task: PowerShell@2
      name: test
      inputs:
        targetType: inline
        script: |
          $ado_environment = "OneStream Tony Test Inc"
          Write-Output "##vso[task.setvariable variable=ado_environment;isOutput=true]$ado_environment"
          Write-Host "Environment is $ado_environment"
          name: Teo
- stage: Two
  jobs:
  - deployment: B
  displayName: deploy_to_env
  pool:
   vmImage: ubuntu-latest
   environment: 'ado_environment'
   strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world

