trigger:
  branches:
    include:
    - master

stages:
- stage: One
  jobs:
  - job: A
  pool:
   vmImage: ubuntu-latest
  steps:
    - task: PowerShell@2
      name: test
      inputs:
        targetType: inline
        script: |
          $ado_environment = "OneStream Tony Test Inc"
          Write-Output "##vso[task.setvariable variable=ado_environment;isOutput=true]$ado_environment"
          Write-Host "Environment is $ado_environment"
          name: Teo
- stage: Two
  jobs:
  - deployment: B
  displayName: deploy_to_env
  pool:
   vmImage: ubuntu-latest
   environment: 
   name: Test
   strategy:
    # Default deployment strategy, more coming...
    runOnce:
      deploy:
        steps:
        - checkout: self 
        - script: echo my first deployment