trigger:
  branches:
    include:
    - master
pool:
  vmImage: ubuntu-latest
stages:
- stage: One
  jobs:
  - job: A
    steps:
    - task: PowerShell@2
      name: test
      inputs:
        targetType: inline
        script: |
          $ado_environment = "OneStream Tony Test Inc"
          Write-Output "##vso[task.setvariable variable=ado_environment;isOutput=true]$ado_environment"
          Write-Host "Environment is $ado_environment"
- stage: Two
  jobs:
  - deployment: B
    environment:
      name: ts
    variables:
    - name: varFromA
      value: $[ stageDependencies.One.A.outputs['test.ado_environment'] ]
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            inputs:
              script: echo $(varFromA)

