# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
- name: PipelineResource
  value: CI
- name: BuildArtifact
  value: NugetPackages

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: 30f35852-3f7e-4c0c-9a88-e127b4f97211@1
  inputs:
    buildType: 'current'
    downloadType: 'single'
    downloadPath: '$(System.ArtifactsDirectory)'
