# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- Test_Server_Path_Var
pool:
  vmImage: 'locals'

- task: DownloadSecureFile@1
  inputs:
    secureFile: '$(Build.DefinitionName)'